# Generated by Django 3.2.5 on 2021-07-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pf_pic',
            field=models.ImageField(default='Pico/images/default-pic.png', upload_to='images/'),
        ),
    ]
