# Generated by Django 3.2.5 on 2021-07-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_profile_pf_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pf_pic',
            field=models.ImageField(default='default-pic.jpg', upload_to='images/'),
        ),
    ]
