# Generated by Django 3.2.5 on 2021-07-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_profile_pf_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='link_fb',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='link_insta',
        ),
        migrations.AddField(
            model_name='profile',
            name='fb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='insta',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
