# Generated by Django 3.2.5 on 2021-07-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0003_rename_c_name_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.CharField(max_length=300),
        ),
    ]
