# Generated by Django 3.2.5 on 2021-08-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
