# Generated by Django 3.2.5 on 2021-08-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0008_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='images_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
