# Generated by Django 3.2.6 on 2021-11-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0011_image_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
